spring:
  datasource:
    username: root
    password: xxxxxx
    url: jdbc:mysql://localhost:3306/online_teaching?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
